# CUDA 12.1 対応のPyTorch公式イメージ
FROM pytorch/pytorch:2.1.2-cuda12.1-cudnn8-runtime

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential

# transformers等をインストール
RUN pip install --no-cache-dir transformers accelerate

COPY . /app

CMD ["python3", "-u", "server.py"]