# 従来どおり軽量なCPU版
FROM python:3.9-slim

WORKDIR /app
RUN apt-get update && apt-get install -y build-essential
RUN pip install --no-cache-dir torch transformers accelerate --extra-index-url https://download.pytorch.org/whl/cpu

COPY . /app
CMD ["tail", "-f", "/dev/null"]